import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import os from "node:os";
import { mkdtemp, rm, stat, writeFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Presentation } from "./presentation.js";
import { md } from "./rich-text.js";
import { CustomSlide } from "./custom-slide.js";
import { PptxPackage } from "./pptx-package.js";
import { getSlideEntries } from "./ooxml.js";
import { C, FONTS } from "./design.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATES = path.resolve(HERE, "..", "templates");
const ASSETS = path.resolve(HERE, "..", "assets");
const ICONS = path.join(ASSETS, "icons");

const EMU_PER_IN = 914400;
const emu = (inches: number) => Math.round(inches * EMU_PER_IN);

// A 1x1 transparent PNG, used to exercise the replaceImage override without
// depending on any binary asset shipped in the repo.
const TINY_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M8AAAMBAQDJ/pLvAAAAAElFTkSuQmCC",
  "base64"
);

// Warnings that depend on the environment (fonts installed, LibreOffice present)
// and never indicate an actual build defect.
const ENV_WARNINGS = new Set(["font-not-embedded", "screenshots-skipped"]);
// Warnings the deck emits by design as it records what it built.
const INFO_WARNINGS = new Set(["custom-slide-generated"]);

test("integration: templates + custom slides + every override, verified end-to-end", async (t) => {
  const dir = await mkdtemp(path.join(os.tmpdir(), "pptx-integration-"));
  t.after(() => rm(dir, { recursive: true, force: true }));

  const pngPath = path.join(dir, "logo.png");
  await writeFile(pngPath, TINY_PNG);

  const deck = new Presentation({
    title: "Integration Deck",
    templateLibrary: TEMPLATES,
    projectDir: dir,
    assetsDir: ASSETS
  });

  // --- Slide 1: title-cover template with styled/moved text + an inserted shape.
  deck.addSlideFromTemplate({
    templateName: "title-cover",
    variables: {
      "overline-label": "Integration Report",
      "your-presentation-title-goes-here": "Everything, verified",
      "a-short-subtitle-that-sets-up-the-st": "Templates and custom slides in one deck."
    },
    overrides: [
      { op: "styleText", target: "your-presentation-title-goes-here", color: "#FF0000", fontSize: 40, fontFace: "Georgia" },
      { op: "move", target: "a-short-subtitle-that-sets-up-the-st", x: 1.0, y: 4.0 },
      {
        op: "addText",
        id: "cta-note",
        text: "Generated by the integration test",
        x: 0.75,
        y: 4.7,
        w: 8.75,
        h: 0.4,
        style: { color: "#123456", fontSize: 12, bold: true, fontFace: "Verdana" }
      }
    ]
  });

  // --- Slide 2: a rich custom slide on a dark background.
  deck.addCustomSlide(
    new CustomSlide({
      name: "system-architecture",
      background: "dark",
      requiredFonts: [FONTS.sans, FONTS.mono],
      draw: async ({ slide, helpers, pageNum, design }) => {
        helpers.addHeader(slide, "System architecture", { light: false });
        helpers.addCodePanel(slide, {
          code: "const total = sum(items)\n// reduce over the batch\nreturn total",
          x: 0.75,
          y: 1.2,
          w: 4.2,
          maxH: 2.5
        });
        helpers.addCard(slide, {
          x: 5.3,
          y: 1.2,
          w: 3.9,
          h: 1.1,
          heading: "Ingest",
          body: "Clone real slides into the library.",
          accent: design.colors.accent
        });
        helpers.addCard(slide, {
          x: 5.3,
          y: 2.5,
          w: 3.9,
          h: 1.1,
          heading: "Compile",
          body: "Fill fields and merge into one deck."
        });
        helpers.addArrow(slide, { from: { x: 5.0, y: 1.75 }, to: { x: 5.3, y: 1.75 } });
        helpers.addConnector(slide, {
          points: [
            { x: 1.0, y: 4.0 },
            { x: 3.0, y: 4.0 },
            { x: 3.0, y: 4.6 }
          ]
        });
        await helpers.addIcon(slide, "rocket", { x: 0.75, y: 4.3, w: 0.5, h: 0.5 }, { color: design.colors.accent });
        helpers.addFooter(slide, pageNum, { light: false });
      }
    })
  );

  // --- Slide 3: content-lead-bullets template with markdown, hide, resize, addIcon.
  deck.addSlideFromTemplate({
    templateName: "content-lead-bullets",
    variables: {
      "section-header": "Key results_",
      "a-lead-statement-that-frames-the-thr": md("**Bold** lead and *italic* detail"),
      "first-supporting-point-that-backs-up": "Cloned every field\nMerged both kinds of slide\nValidated the package"
    },
    overrides: [
      { op: "hide", target: "2" },
      { op: "resize", target: "a-lead-statement-that-frames-the-thr", w: 9.0, h: 1.2 },
      { op: "addIcon", id: "star-icon", icon: path.join(ICONS, "star.svg"), x: 8.9, y: 0.3, w: 0.4, h: 0.4 }
    ]
  });

  // --- Slide 4: a custom slide on a bespoke background colour.
  deck.addCustomSlide(
    new CustomSlide({
      name: "closing",
      background: { color: "#0EA5E9" },
      draw: ({ slide, helpers, design }) => {
        helpers.addTextBlock(
          slide,
          [{ text: "Thanks for reading" }],
          { x: 0.75, y: 2.0, w: 8.75, h: 1.0 },
          { fontSize: 36, color: design.colors.white, fontFace: FONTS.serif }
        );
        helpers.addImagePlaceholder(slide, {
          x: 0.75,
          y: 3.2,
          w: 3.0,
          h: 1.5,
          caption: "Team photo goes here"
        });
        helpers.addVectorIcon(
          slide,
          '<svg viewBox="0 0 24 24"><path d="M4 12 L12 4 L20 12"/></svg>',
          { x: 8.5, y: 0.4, w: 0.6, h: 0.6 },
          { color: design.colors.white }
        );
      }
    })
  );

  // --- Slide 5: content-lead-bullets reused, delete a field then addSvg +
  // replaceImage chained on the inserted picture. Reusing a non-first template
  // loads a fresh single-slide package from disk, so there is no cross-slide
  // bleed (that only happens when the very first template is reused).
  deck.addSlideFromTemplate({
    templateName: "content-lead-bullets",
    variables: {
      "a-lead-statement-that-frames-the-thr": "Appendix and extra material.",
      "first-supporting-point-that-backs-up": "One more note"
    },
    overrides: [
      { op: "delete", target: "section-header" },
      { op: "addSvg", id: "deco", path: path.join(ICONS, "check.svg"), x: 8.5, y: 0.4, w: 0.6, h: 0.6 },
      { op: "replaceImage", target: "deco", path: pngPath }
    ]
  });

  const report = await deck.render({
    output: "deck.pptx",
    report: "report.md",
    progress: false
  });

  // ---------------------------------------------------------------------------
  // Report-level checks.
  // ---------------------------------------------------------------------------
  const outputPath = path.join(dir, "deck.pptx");
  assert.ok((await stat(outputPath)).size > 0, "output file is non-empty");
  assert.equal(report.slidesBuilt, 5);
  assert.deepEqual(report.templatesUsed, ["title-cover", "content-lead-bullets", "content-lead-bullets"]);
  assert.deepEqual(report.customSlidesUsed, ["system-architecture", "closing"]);

  const unexpected = report.warnings.filter(
    (w) => !ENV_WARNINGS.has(w.code) && !INFO_WARNINGS.has(w.code)
  );
  assert.deepEqual(unexpected, [], `unexpected warnings: ${JSON.stringify(unexpected, null, 2)}`);

  // The build report was written and mentions the pieces we assembled.
  const reportMd = await readFile(path.join(dir, "report.md"), "utf8");
  assert.match(reportMd, /Slides built: 5/);
  assert.match(reportMd, /system-architecture/);

  // ---------------------------------------------------------------------------
  // Reload the deck and inspect slides in presentation order.
  // ---------------------------------------------------------------------------
  const pkg = await PptxPackage.load(outputPath);
  const entries = await getSlideEntries(pkg);
  assert.equal(entries.length, 5, "deck has exactly the five slides we built");

  const xml = await Promise.all(
    entries.map((e) => pkg.text(`ppt/slides/slide${e.slideNumber}.xml`))
  );
  const [s1, s2, s3, s4, s5] = xml;
  const text = (s: string) =>
    [...s.matchAll(/<a:t>([\s\S]*?)<\/a:t>/g)].map((m) => m[1]).join("");

  // --- Slide 1: title-cover with overrides. --------------------------------
  assert.match(text(s1), /Everything, verified/);
  assert.match(text(s1), /Integration Report/);
  assert.match(text(s1), /Templates and custom slides in one deck\./);
  // styleText rewrote colour, size and typeface inside the title shape.
  assert.ok(s1.includes('val="FF0000"'), "title colour restyled to FF0000");
  assert.ok(s1.includes('sz="4000"'), "title font size restyled to 40pt");
  assert.ok(s1.includes('typeface="Georgia"'), "title typeface restyled to Georgia");
  // move rewrote the subtitle's offset to exactly 1.0in / 4.0in.
  assert.ok(s1.includes(`<a:off x="${emu(1.0)}" y="${emu(4.0)}"/>`), "subtitle moved to (1,4)");
  // addText inserted a brand-new shape carrying our id, text and styling.
  assert.ok(s1.includes('name="cta-note"'), "addText shape present by id");
  assert.match(text(s1), /Generated by the integration test/);
  assert.ok(s1.includes('val="123456"'), "addText colour applied");
  assert.ok(s1.includes('typeface="Verdana"'), "addText typeface applied");
  assert.ok(/<a:rPr[^>]*\bb="1"/.test(s1), "addText bold applied");

  // --- Slide 2: dark custom slide. -----------------------------------------
  assert.ok(s2.includes(C.ink), `dark background uses ink colour ${C.ink}`);
  assert.match(text(s2), /System architecture/);
  assert.match(text(s2), /const total = sum\(items\)/);
  assert.match(text(s2), /reduce over the batch/);
  assert.match(text(s2), /Ingest/);
  assert.match(text(s2), /Compile/);
  assert.match(text(s2), /Clone real slides into the library\./);
  // The rocket icon renders as an editable native custom-geometry shape.
  assert.ok(s2.includes("custGeom"), "addIcon produced a native custGeom shape");
  // Arrows/connectors render as line shapes with arrowheads.
  assert.ok(/<a:tailEnd[^>]*type="triangle"/.test(s2), "arrow has a triangular head");

  // --- Slide 3: content template with markdown + overrides. ----------------
  assert.match(text(s3), /Key results/);
  // Markdown is flattened to plain text for template fields.
  assert.match(text(s3), /Bold lead and italic detail/);
  assert.ok(!text(s3).includes("**"), "markdown asterisks were stripped");
  for (const line of ["Cloned every field", "Merged both kinds of slide", "Validated the package"]) {
    assert.ok(text(s3).includes(line), `bullet present: ${line}`);
  }
  // hide set the footer shape hidden.
  assert.ok(/<p:cNvPr[^>]*hidden="1"/.test(s3), "hide override set hidden=1");
  // resize rewrote the lead's extent to 9.0in x 1.2in.
  assert.ok(s3.includes(`<a:ext cx="${emu(9.0)}" cy="${emu(1.2)}"/>`), "lead resized to 9x1.2");
  // addIcon added an svg image referenced by the slide.
  assert.ok(s3.includes("<a:blip"), "addIcon (svg) inserted a picture with a blip");

  // --- Slide 4: custom slide with a bespoke background. --------------------
  assert.ok(s4.includes("0EA5E9"), "custom background colour applied");
  assert.match(text(s4), /Thanks for reading/);
  assert.match(text(s4), /Team photo goes here/);
  assert.ok(s4.includes("custGeom"), "addVectorIcon produced a native shape");
  assert.ok(/roundRect|prst="roundRect"/.test(s4), "image placeholder is a rounded rectangle");

  // --- Slide 5: delete + addSvg + replaceImage. ----------------------------
  assert.ok(!text(s5).includes("Section header"), "deleted section-header text is gone");
  assert.match(text(s5), /Appendix and extra material\./);
  assert.ok(s5.includes('name="deco"'), "addSvg shape present by id");
  assert.ok(s5.includes("<a:blip"), "picture shape carries a blip after replaceImage");

  // ---------------------------------------------------------------------------
  // Package-wide structural checks.
  // ---------------------------------------------------------------------------
  const contentTypes = await pkg.text("[Content_Types].xml");
  assert.ok(/Extension="svg"/.test(contentTypes), "svg content type registered");
  assert.ok(/Extension="png"/.test(contentTypes), "png content type registered");

  const media = pkg.files("ppt/media/");
  assert.ok(media.some((f) => f.endsWith(".svg")), "an svg media part exists");
  assert.ok(media.some((f) => f.endsWith(".png")), "the replacement png media part exists");

  // The replacement png bytes actually landed in the package.
  const pngInPkg = media.find((f) => f.endsWith(".png"))!;
  const pngBytes = await pkg.bytes(pngInPkg);
  assert.deepEqual(pngBytes, TINY_PNG, "png media matches the source bytes");

  // Every slide relationship resolves and the shared support chain is intact.
  assert.ok(pkg.has("ppt/presentation.xml"));
  assert.ok(pkg.has("ppt/_rels/presentation.xml.rels"));
  assert.ok(pkg.files("ppt/slideLayouts/").some((f) => /slideLayout\d+\.xml$/.test(f)));
  assert.ok(pkg.files("ppt/slideMasters/").some((f) => /slideMaster\d+\.xml$/.test(f)));
  assert.ok(pkg.files("ppt/theme/").some((f) => /theme\d+\.xml$/.test(f)));

  // Each slide's XML is well-formed enough to parse its shape tree.
  for (const s of xml) {
    assert.match(s, /<p:spTree>/, "slide has a shape tree");
    assert.equal((s.match(/<p:sp>/g) ?? []).length, (s.match(/<\/p:sp>/g) ?? []).length, "sp tags balanced");
  }

  // ---------------------------------------------------------------------------
  // Screenshots: if LibreOffice rendered them, there is exactly one per slide.
  // ---------------------------------------------------------------------------
  const screenshotsSkipped = report.warnings.some((w) => w.code === "screenshots-skipped");
  if (!screenshotsSkipped) {
    assert.equal(report.screenshots.length, 5, "one screenshot per slide");
    for (const shot of report.screenshots) {
      assert.ok((await stat(shot)).size > 0, `screenshot is non-empty: ${shot}`);
    }
  }
});
